name: Add New Activity
description: Request to add a new extracurricular activity to the system
title: "[Activity] Add new activity: "
labels: ["enhancement", "activity"]
assignees:
  - Copilot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a new activity! Please provide the details below so we can add it to the system.
        
  - type: input
    id: activity_name
    attributes:
      label: Activity Name
      description: What is the name of the new activity?
      placeholder: e.g., Robotics Club, Photography Club, Debate Team
    validations:
      required: true
      
  - type: textarea
    id: activity_description
    attributes:
      label: Activity Description
      description: Provide a brief description of what students will do in this activity
      placeholder: e.g., Students will learn basic robotics principles, build robots, and compete in local competitions
    validations:
      required: true
      
  - type: dropdown
    id: activity_days
    attributes:
      label: Meeting Days
      description: Which days will this activity meet?
      multiple: true
      options:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
    validations:
      required: true
      
  - type: input
    id: start_time
    attributes:
      label: Start Time
      description: What time does the activity start? (Use 24-hour format, e.g., 15:30 for 3:30 PM)
      placeholder: "15:30"
    validations:
      required: true
      
  - type: input
    id: end_time
    attributes:
      label: End Time
      description: What time does the activity end? (Use 24-hour format)
      placeholder: "17:00"
    validations:
      required: true
      
  - type: input
    id: max_participants
    attributes:
      label: Maximum Participants
      description: How many students can participate in this activity?
      placeholder: "20"
    validations:
      required: true
      
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other details about the activity (equipment needed, prerequisites, etc.)
      placeholder: Students should bring their own laptops. No prior experience required.
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        - [ ] Activity appears in the activities list
        - [ ] Students can register for the activity
        - [ ] Activity shows correct schedule and participant limits
        - [ ] Activity displays properly on both desktop and mobile
        
        ## Technical Implementation Notes
        The activity should be added to the `initial_activities` dictionary in `src/backend/database.py` with the following structure:
        ```python
        "Activity Name": {
            "description": "Description text",
            "schedule": "Days, Time - Time",
            "schedule_details": {
                "days": ["Day1", "Day2"],
                "start_time": "HH:MM",
                "end_time": "HH:MM"
            },
            "max_participants": number,
            "participants": []
        }
        ```