blank_issues_enabled: false
contact_links:
  - name: 📚 Development Documentation
    url: https://github.com/leonardobora/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Technical documentation for developers and advanced users
  - name: 💬 General Questions
    url: https://github.com/leonardobora/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or start discussions about the activity management system